<?php

namespace EventsBundle\Repository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTitle($nom)
    {
        $q=$this->createQueryBuilder('m')
            ->where('m.nom LIKE :nom')
            ->setParameter(':nom',"%$nom%");
        return $q->getQuery()->getResult();
    }

    public function findMulti($find)
    {
        $q=$this->createQueryBuilder('m')
            ->where('m.nom LIKE :find')->orWhere('m.description LIKE :find')->orWhere('m.lieu LIKE :find')
            ->setParameter(':find',"%$find%");
        return $q->getQuery()->getResult();
    }

}
