<?php

namespace EventsBundle\Repository;

use EventsBundle\Entity\Participation;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEvents($id)
    {
        $req=$this->getEntityManager()
            ->createQuery("select count(u) from EventsBundle:Participation u WHERE u.events=:id")
            ->setParameter('id',$id);
        return $req->getResult();
    }

}
